#! /bin/bash

# GemInABox
# Maintainer: David Hooey

### BEGIN INIT INFO
# Provides:          geminabox
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Gem in a Box
### END INIT INFO

USER=rubyuser
ENV=production
APP_ROOT="/opt/kobanzame/current"
PUMA_PID="$APP_ROOT/tmp/pids/puma.pid"
PUMA_UP="~/.rbenv/shims/bundle exec puma --environment development -C $APP_ROOT/config/puma.rb -d"
NAME="puma"
DESC="GemInABox service"

check_pid(){
    if [ -f $PUMA_PID ]; then
        PID=`cat $PUMA_PID`
        STATUS=`ps aux | grep $PID | grep -v grep | wc -l`
    else
        STATUS=0
        PID=0
    fi
}

start() {
    cd $APP_ROOT
    check_pid
    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
        # Program is running, exit with error code 1.
        echo "Error! $DESC $NAME is currently running!"
        exit 1
    else
        if [ `whoami` = root ]; then
            sudo -u $USER -H bash -l -c "$PUMA_UP"
#            touch $PUMA_PID
#            $PUMA_UP
            echo "$DESC started"
        fi
    fi
}

stop() {
    sudo -u $USER -H bash -l -c "bundle exec pumactl --state tmp/pids/puma.state stop"
#    cd $APP_ROOT
#    check_pid
#    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
#        ## Program is running, stop it.
#        kill -QUIT `cat $PUMA_PID`
##        rm $PUMA_PID >> /dev/null
#        echo "$DESC stopped"
#    else
#        ## Program is not running, exit with error.
#        echo "Error! $DESC not started!"
#        exit 1
#    fi
}

reload() {
    cd $APP_ROOT
    check_pid
    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
        ## Program is running, stop it.
        kill -SIGUSR2 `cat $PUMA_PID`
        echo "$DESC reload"
    else
        ## Program is not running, exit with error.
        echo "Error! $DESC not started!"
        exit 1
    fi
}

status() {
    cd $APP_ROOT
    check_pid
    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
        echo "$DESC with PID $PID is running."
    else
        echo "$DESC is not running."
        exit 1
    fi
}

## Check to see if we are running as root first.
## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
fi

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        start
        stop
        ;;
    reload)
        reload
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: sudo service geminabox {start|stop|restart|reload|status}" >&2
        exit 1
        ;;
esac

exit 0

